# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5a59166e0084733ec80d8afec84fca9de3f2846ab55fff945d3ce452e52aaea73066ba537ca6597bb1ee90e5074b9b1e32cff01284f55f84b8541948d382955

test:
  secret_key_base: edf10e065534d5b3bf4aa8961f0e5f26da747a30784ec7d51683abd8131965b01ba0b53da0493d843eeb7b95bdfd79b53e45df223df3507650ba253b35ea8f34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 4b241b4b65200869a7a40ea15e8ed58b616c8f1f8968a424813ae854149394a30becac33942bcbb92cefa2be28041d07e5efeef9b94608762512aedf7e996435
